// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// check_which_state_2_C
NumericVector check_which_state_2_C(NumericMatrix x, NumericMatrix x2);
RcppExport SEXP TTTrcpp_check_which_state_2_C(SEXP xSEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(check_which_state_2_C(x, x2));
    return rcpp_result_gen;
END_RCPP
}
// learn_progress_C
double learn_progress_C(NumericVector x);
RcppExport SEXP TTTrcpp_learn_progress_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(learn_progress_C(x));
    return rcpp_result_gen;
END_RCPP
}
// which_equal_C
NumericVector which_equal_C(NumericVector x, double k);
RcppExport SEXP TTTrcpp_which_equal_C(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(which_equal_C(x, k));
    return rcpp_result_gen;
END_RCPP
}
