# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

base3_to_decimal <- function(x) {
    .Call('TTTrcpp_base3_to_decimal', PACKAGE = 'TTTrcpp', x)
}

check_status_C <- function(x, turn) {
    .Call('TTTrcpp_check_status_C', PACKAGE = 'TTTrcpp', x, turn)
}

check_which_state_2_C <- function(x, x2) {
    .Call('TTTrcpp_check_which_state_2_C', PACKAGE = 'TTTrcpp', x, x2)
}

learn_progress_C <- function(x) {
    .Call('TTTrcpp_learn_progress_C', PACKAGE = 'TTTrcpp', x)
}

reflection_C <- function(x, direction) {
    .Call('TTTrcpp_reflection_C', PACKAGE = 'TTTrcpp', x, direction)
}

rotate_90_C <- function(x) {
    .Call('TTTrcpp_rotate_90_C', PACKAGE = 'TTTrcpp', x)
}

which_equal_C <- function(x, k) {
    .Call('TTTrcpp_which_equal_C', PACKAGE = 'TTTrcpp', x, k)
}

which_equal_C_2 <- function(x, k) {
    .Call('TTTrcpp_which_equal_C_2', PACKAGE = 'TTTrcpp', x, k)
}

